### ISSUE TITLE
How does this operator relate to the 'official' one?

### ISSUE THREAD

**Issue by lion7** [openshift/cluster-capi-operator#37]
Hi all.

I'm trying to integrate Cluster API into my project and I'm a bit confused about this operator compared to the one created by the Kubernetes Cluster API SIG group. That one is based on [this proposal](https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/docs/capi-operator-proposal.md) and can be found at https://github.com/kubernetes-sigs/cluster-api-operator/. I also noted that https://github.com/openshift/cluster-api-operator is fork of said operator. This is what makes me confused 🤔 

The end goal of my project is to let users automatically provision a Kubernetes cluster of their choice on hardware I own (so basically, cluster as a service). I'd like OKD to be one of the choices available. Technically I want to exclusively use Cluster API for the povisioning process, so without Machine API or any other specific tooling. In my search I stumbled upon https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/cluster-api-integration.md, which describes exactly what I need for the OKD part. But that is only the proposal and I'm trying to find if someone already started on the actual implementation.

Any suggestions on repositories I should watch / follow? Or perhaps I'm just looking in totally the wrong place?

**Comment by alexander-demichev** [comment]
Hi, 
This operator is made to deploy Clust API components on an openshift cluster, it leverages upstream operator API and performs some openshift specific stuff for configuring CAPI, like creating repositories for reading manifests, etc.

You might want to look at https://github.com/openshift/hive for cluster management because the state of CAPI integration at the moment is far from being production ready.

**Comment by lion7** [comment]
Thanks for the explanation. Hive looks like the thing I was looking for, a big thank you for the link 🥳
